---
- hosts: all

  tasks:
    - name: create manifests
      command:
        cmd: "{{ openshift_build_path }}/openshift-install create manifests --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"

    - name: create cluster
      command:
        cmd: "{{ openshift_build_path }}/openshift-install create cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
      async: 3600
      poll: 60
      register: result

    - name: print output
      debug:
        msg: "{{ result.stderr.split('\n') }}"
      when: result is succeeded
