---
- hosts: all

  tasks:
    - name: create manifests
      command:
        cmd: "{{ openshift_build_path }}/openshift-install create manifests --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"

    - name: create cluster
      command:
        cmd: "{{ openshift_build_path }}/openshift-install create cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
      register: cmd_output

    - name: print output
      debug:
        msg: "{{ cmd_output.stderr.split('\n') }}"
