---
- hosts: all

  tasks:
    - name: destroy cluster
      command:
        cmd: "{{ openshift_build_path }}/openshift-install destroy cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
      register: result

    - name: print output
      debug:
        msg: "{{ result.stderr.split('\n') }}"
      when: result is succeeded

    - name: remove installer directory
      file:
        path: "{{ openshift_installer_path }}"
        state: absent
      when: result is succeeded
