---
- hosts: all

  tasks:
    - name: destroy cluster
      command:
        cmd: "{{ openshift_build_path }}/openshift-install destroy cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
      register: cmd_output

    - name: print output
      debug:
        msg: "{{ cmd_output.stderr }}"
