---
- hosts: all

  tasks:
  - name: backup the kubeconfig file
    copy:
      src: "{{ openshift_build_path }}/auth/kubeconfig"
      remote_src: yes
      dest: "{{ openshift_build_path }}/auth/kubeconfig.bak"

  - name: create updated kubeconfig
    script:
      cmd: update_kubeconfig.sh "openshift-{{ cluster_name }}"
