---
- name: set build path
  set_fact:
    openshift_build_path: "/home/ec2-user/openshift-{{ cluster_name }}/build"

- name: Get default ingress controller
  k8s_info:
    api_version: v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    kubeconfig: "{{ openshift_build_path }}/auth/"
  register: le_wildcard

- name: set letsencrypt facts
  set_fact:
    le_wildcard: "*.{{le_wildcard.resources[0].status.domain}}"
    le_api: "{{ le_wildcard.resources[0].status.domain | regex_replace('^apps\\.', 'api.') }}"
    le_secret_name: "le-certs-{{ ansible_date_time.date }}"

