---

- name: Set default variables for automated build (facts)
  set_fact:
    openshift_build_path: "/home/ec2-user/openshift-{{ cluster_name }}/build"

- name: create build directory for deployment artifacts
  file:
    path: "{{ openshift_build_path }}"
    state: directory
    mode: 0700

- name: Set installer type
  set_fact:
    openshift_binary_type: "linux"

- name: download and extract openshift installer
  unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-install-{{ openshift_binary_type }}-{{ openshift_version }}.tar.gz
    dest: "{{ openshift_build_path }}"
    remote_src: yes

- name: download and extract openshift oc cli tool
  unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-{{ openshift_binary_type }}-{{ openshift_version }}.tar.gz
    dest: "{{ openshift_build_path }}"
    remote_src: yes

- name: extract openshift odo developer cli tool
  unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/odo/v{{ openshift_odo_version }}/odo-{{ openshift_binary_type }}-amd64.tar.gz
    dest: "{{ openshift_build_path }}"
    remote_src: yes
  when: openshift_installer_type != "automation"

- name:  adding '+x' execute permissions because odo by default doesn't have execute
  file:
    path: "{{ openshift_build_path }}/odo"
    mode: a+x
  when: openshift_installer_type != "automation"

- name: generate cluster ssh key pair
  openssh_keypair:
    path: "{{ openshift_build_path }}/{{ openshift_cluster_name }}-key"
    size: 4096
    type: rsa

- name: get the public key contents
  slurp:
    src: "{{ openshift_build_path }}/{{ openshift_cluster_name }}-key.pub"
  register: pub_key

- name: set ssh key fact
  set_fact:
    openshift_node_ssh_public_key: "{{ pub_key.content | b64decode }}"

- name: create openshift install-config.yaml file
  template:
    src: "install-config.yaml.j2"
    dest: "{{ openshift_build_path }}/install-config.yaml"

- name: backup install-config.yaml file as install-config.yaml.backup
  copy:
    remote_src: yes
    src: "{{ openshift_build_path }}/install-config.yaml"
    dest: "{{ openshift_build_path }}/install-config.yaml.backup"

- name: Write OCP version to openshift_version.txt
  copy: content="{{ openshift_version }}" dest="{{ openshift_build_path }}/openshift_version.txt"
  when: openshift_installer_type == "automation"

- debug:
    msg:
      - "For a cli demonstration on the provisioner, "
      - "execute the following command to deploy the openshift cluster"
      - "--------------------"
      - "{{ openshift_build_path }}/openshift-install create cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
